version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - static_volume:/app/staticfiless
    expose:
      - 8000
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiless
    depends_on:
      - web

volumes:
  static_volume:
